"use client";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sideMenu";
import { ApolloProvider } from "@apollo/client";
import client from "./auth/ApolloProviderWithAuth";

import SaveUserAutomatically from "./actions/user";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  

  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased`}>
        <UserProvider>
          <ApolloProvider client={client}>
            <Navbar />
            <SaveUserAutomatically />
            {children}
          </ApolloProvider>
        </UserProvider>
      </body>
    </html>
  );
}
